//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiCep_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definiciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Definiciones()
        {
            this.Ejemplos = new HashSet<Ejemplos>();
            this.Imagenes = new HashSet<Imagenes>();
            this.Temas = new HashSet<Temas>();
            this.TutorialesYouTube = new HashSet<TutorialesYouTube>();
        }
    
        public int IDDefinicion { get; set; }
        public string Titulo { get; set; }
        public string IDAutor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Texto { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ejemplos> Ejemplos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagenes> Imagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temas> Temas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorialesYouTube> TutorialesYouTube { get; set; }
    }
}
